config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # :user，跟 resources :users 相比，单数的路由少了 index action，并且网址上不会有 ID，路由方法也皆为单数不需要参数，例如 user_path、edit_user_path。
  # 会这样设计的原因是对前台用户而言，
  # 编辑用户资料就是编辑自己的资料，所以这个单数的用意是指唯一自己，用户也不能修改其他人的资料，因此在controller 里面是写@user = current_user，而不是根据params[:id] 去捞不同用户。
  resource :user

  resources :events do
    resources :registrations do
      member do
        get 'steps/1' => 'registrations#step1', :as => :step1
        patch 'steps/1/update' => 'registrations#step1_update', :as => :update_step1
        get 'steps/2' => 'registrations#step2', :as => :step2
        patch 'steps/2/update' => 'registrations#step2_update', :as => :update_step2
        get 'steps/3' => 'registrations#step3', :as => :step3
        patch 'steps/3/update' => 'registrations#step3_update', :as => :update_step3
      end
    end
  end

  namespace :admin do
    root 'events#index'

    resources :versions do
      post :undo
    end

    resources :events do
      resources :registrations, controller: 'event_registrations'
      resources :tickets, controller: 'event_tickets'
      member do
        post :reorder
      end
      collection do
        post :bulk_update
      end
    end
    resources :users do
      # 因为默认的 controller 的命名是 profiles，这里我们偏好自定义命名改为user_profiles
      resource :profile, controller: 'user_profiles'
    end
  end

  root 'events#index'
  get '/faq', to: 'pages#faq'
end

app/models/event.rb
class Event < ApplicationRecord
  mount_uploaders :images, EventImageUploader
  serialize :images, JSON
  # 排序
  include RankedModel
  ranks :row_order

  has_many :registrations, dependent: :destroy
  has_many :tickets, dependent: :destroy, inverse_of: :event
  belongs_to :category, optional: true
  # 某些版本的Rails 有个accepts_nested_attributes_for 的bug 让has_many 故障了，需要额外补上inverse_of 参数，不然存储时会找不到tickets
  accepts_nested_attributes_for :tickets, reject_if: :all_blank, allow_destroy: true

  validates_presence_of :name, :random_id
  validates_uniqueness_of :random_id, message: '必须不相同'
  validates_format_of :random_id, with: /\A[a-z0-9\-]+\z/, message: '无效的格式'

  before_validation :generate_random_id, on: :create

  # 加上状态字段的验证
  STATUS = %W[\u8349\u7A3F \u516C\u5F00 \u79C1\u4EBA].freeze
  validates_inclusion_of :status, in: STATUS

  # 在调用路由方法时，Rails 默认都会用 to_param 方法来转换 ID,
  #  def to_param
  #    self.id
  #  end

  def to_param
    # "#{self.id}-#{self.name}"
    random_id
  end

  protected

  def generate_random_id
    self.random_id ||= SecureRandom.uuid
  end
end

app/controllers/admin/event_registrations_controller.rb
require 'csv'

class Admin::EventRegistrationsController < ApplicationController
  before_action :find_event
  before_action :find_registration, only: %i[edit update destroy]
  before_action :require_editor!

  def index
    # 字段查询
    @q = @event.registrations.ransack(params[:q])
    @registrations = @q.result.includes(:ticket).order('id DESC').page(params[:page])
    # 单选
    if params[:status].present? && Registration::STATUS.include?(params[:status])
      @registrations = @registrations.by_status(params[:status])
    end
    if params[:ticket_id].present?
      @registrations = @registrations.by_ticket(params[:ticket_id])
    end

    # 多选
    if Array(params[:statuses]).any?
      @registrations = @registrations.by_status(params[:statuses])
    end

    if Array(params[:ticket_ids]).any?
      @registrations = @registrations.by_ticket(params[:ticket_ids])
    end

    # 时间段查询
    if params[:start_on].present?
      @registrations = @registrations.where('created_at >= ?', Date.parse(params[:start_on]).beginning_of_day)
    end

    if params[:end_on].present?
      @registrations = @registrations.where('created_at <= ?', Date.parse(params[:end_on]).end_of_day)
    end

    # 字段查询，会要完全一模一样(exact match)才会筛选出来
    if params[:registration_id].present?
      @registrations = @registrations.where(id: params[:registration_id].split(','))
    end

    respond_to do |format|
      format.html
      format.xlsx
      format.csv do
        @registrations = @registrations.reorder('id ASC')
        csv_string = CSV.generate do |csv|
          csv << ["报名ID", "票种", "姓名", "状态", "Email", "报名时间"]
          @registrations.each do |r|
            csv << [r.id, r.ticket.name, r.name, t(r.status, scope: 'registration.status'), r.email, r.created_at]
          end
        end
        send_data csv_string, filename: "#{@event.random_id}-registrations-#{Time.now.to_s(:number)}.csv"
      end
    end
  end

  def edit; end

  def new
    @registration = @event.registrations.new
  end

  def destroy
    @registration = @event.registrations.find_by_uuid(params[:id])
    @registration.destroy

    redirect_to admin_event_registrations_path(@event)
  end

  def create
    @registration = @event.registrations.new(registration_params)
    if @registration.save
      flash[:success] = '新增成功！'
      redirect_to admin_event_registrations_path(@event)
    else
      render 'new'
   end
  end

  def update
    if @registration.update(registration_params)
      flash[:success] = '编辑成功'
      redirect_to admin_event_registrations_path(@event)
    else
      render 'edit'
    end
  end

  protected

  def find_event
    @event = Event.find_by_random_id!(params[:event_id])
  end

  def find_registration
    @registration = @event.registrations.find_by_uuid(params[:id])
  end

  def registration_params
    params.require(:registration).permit(:status, :ticket_id, :name, :email, :cellphone, :website, :bio)
  end
end

app/helpers/admin/event_registrations_helper.rb
module Admin::EventRegistrationsHelper
  def registration_filters(options)
    params.permit(:status, :ticket_id).merge(options)
  end
end

app/views/admin/event_registrations/_form.html.erb
<% if @registration.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @registration.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= f.label :票种 %>
   <%= f.select :ticket_id, Ticket.all.map{ |s| [s.name, s.id] }, {}, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :名称 %>
  <%= f.text_field :name, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :状态 %>
  <%= f.text_area :status, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :电子邮箱 %>
  <%= f.text_area :email, :class => "form-control" %>
</div>

app/views/admin/event_registrations/edit.html.erb
<h1>编辑报名资料<</h1>

<%= form_for [:admin, @event, @registration] do |f| %>

  <%= render :partial => "form", :locals => { :f => f } %>

  <div class="form-group">
    <%= f.submit "更新", :class => "btn btn-primary" %>
    <%= link_to "取消", admin_event_registrations_path(@event) %>
  </div>

<% end %>

app/views/admin/event_registrations/index.html.erb
<h1><%= @event.name %> / Registrations</h1>

<p class="text-right">
  <%= link_to "New Registration", new_admin_event_registration_path(@event), :class => "btn btn-primary" %>
</p>


<div class="submenu">
  <%# 样板中如果有大范围暂时需要注解，可以用 <% if false .... <% end %>
  <%# 包起来  %>
  <% if false %>
  <div class="btn-group">
    <%= link_to "全部(#{@event.registrations.size})", admin_event_registrations_path(registration_filters(:status => nil)), :class => "btn btn-success btn-group #{(params[:status].blank?) ? "active" : ""}" %>
    <% Registration::STATUS.each do |s| %>
    <%= link_to t(s, :scope => "registration.status") + " (#{@event.registrations.by_status(s).size})",   admin_event_registrations_path(registration_filters(:status => s)), :class => "btn btn-success btn-group #{(  params[:status] == s) ? "active" : ""}" %>
    <% end %>
  </div>
  <% end %>

  <% if false %>
  <div class="btn-group">
    <%= link_to "全部 (#{@event.registrations.size})", admin_event_registrations_path(registration_filters(:ticket_id => nil)), :class => "btn btn-default btn-group #{(params[:ticket_id].blank?) ? "active" : ""}" %>
    <% @event.tickets.each do |t| %>
    <%= link_to "#{t.name}" "(#{@event.registrations.by_ticket(t).size})", admin_event_registrations_path(registration_filters(:ticket_id => t.id)), :class => "btn btn-default btn-group #{(params[:ticket_id].to_i == t.id) ? "active" : ""}" %>
    <% end %>
  </div>
  <% end %>

  <%# <%= form_tag admin_event_registrations_path(@event), :method => :get do %>
  <%= search_form_for @q, :url => admin_event_registrations_path(@event) do |f| %>
  <%# search_field 是 ransack 独到的方法，后面的 :name_cont 代表 name 这个字段要包含(contains)的关键字 %>
  <p><%= f.search_field :name_cont, :placeholder => "姓名", :class => "form-control" %></p>
  <p><%= f.search_field :email_cont, :placeholder => "电子邮箱", :class => "form-control" %></p>
  <p>
    <%= text_field_tag :registration_id, params[:registration_id], :placeholder => "报名编号，可用,号区隔", :class => "form-control" %>
  </p>

  <p><% Registration::STATUS.each do |s| %>
    <label><%= check_box_tag "statuses[]", s, Array(params[:statuses]).include?(s) %>
      <%= t(s, :scope =>  "registration.status") %> (<%= @event.registrations.by_status(s).size %>)</label>
    <% end %></p>

  <p><% @event.tickets.each do |t| %>
    <label><%= check_box_tag "ticket_ids[]", t.id, Array(params[:ticket_ids]).include?(t.id.to_s) %> <%= t.name %>
      (<%=  @event.registrations.where( :ticket_id => t.id ).size %>)</label>
    <% end %>
  </p>

  <p>
    报名日期：<%= date_field_tag :start_on, params[:start_on] %>～<%= date_field_tag :end_on, params[:end_on] %>
  </p>

  <p class="text-right">
    <%= submit_tag "送出筛选", :class => "btn btn-primary" %>
  </p>
  <% end %>
</div>

<table class="table">
  <tr>
    <th>序号</th>
    <th>票种</th>
    <th>名称</th>
    <th>状态</th>
    <th>电子邮箱</th>
    <th>建立时间</th>
    <th>操作</th>
  </tr>
  <% @registrations.each do |registration| %>
  <tr>
    <td><%= registration.id %></td>
    <td><%= registration.ticket.name %></td>
    <td><%= registration.name %></td>
    <td><%= t( registration.status, :scope => "registration.status") %></td>
    <td><%= registration.email %></td>
    <td><%= registration.created_at %></td>
    <td>
      <%= link_to "编辑", edit_admin_event_registration_path(@event, registration), :class => "btn btn-default" %>
      <%= link_to "删除", admin_event_registration_path(@event, registration), :method => "delete", :data => { :confirm => "Are you sure?" }, :class => "btn btn-danger" %>
  </tr>
  <% end %>
</table>
<%= paginate @registrations %>

<p>
  <%= link_to "汇出 CSV", admin_event_registrations_path(:format => :csv), :class => "btn btn-default" %>
  <%= link_to "汇出 Excel", admin_event_registrations_path(:format => :xlsx), :class => "btn btn-default" %>
</p>

app/views/admin/event_registrations/new.html.erb
<h1>新建报名资料</h1>

<%= form_for [:admin, @event, @registration] do |f| %>

  <%= render :partial => "form", :locals => { :f => f } %>

  <div class="form-group">
    <%= f.submit "创建", :class => "btn btn-primary" %>
    <%= link_to "取消", admin_event_registrations_path(@event) %>
  </div>
<% end %>