config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # :user，跟 resources :users 相比，单数的路由少了 index action，并且网址上不会有 ID，路由方法也皆为单数不需要参数，例如 user_path、edit_user_path。
  # 会这样设计的原因是对前台用户而言，
  # 编辑用户资料就是编辑自己的资料，所以这个单数的用意是指唯一自己，用户也不能修改其他人的资料，因此在controller 里面是写@user = current_user，而不是根据params[:id] 去捞不同用户。
  resource :user

  resources :events do
    resources :registrations do
      member do
        get 'steps/1' => 'registrations#step1', :as => :step1
        patch 'steps/1/update' => 'registrations#step1_update', :as => :update_step1
        get 'steps/2' => 'registrations#step2', :as => :step2
        patch 'steps/2/update' => 'registrations#step2_update', :as => :update_step2
        get 'steps/3' => 'registrations#step3', :as => :step3
        patch 'steps/3/update' => 'registrations#step3_update', :as => :update_step3
      end
    end
  end

  namespace :admin do
    root 'events#index'

    resources :versions do
      post :undo
    end

    resources :events do
      resources :registrations, controller: 'event_registrations'
      resources :tickets, controller: 'event_tickets'
      member do
        post :reorder
      end
      collection do
        post :bulk_update
      end
    end
    resources :users do
      # 因为默认的 controller 的命名是 profiles，这里我们偏好自定义命名改为user_profiles
      resource :profile, controller: 'user_profiles'
    end
  end

  root 'events#index'
  get '/faq', to: 'pages#faq'
end

app/models/event.rb
class Event < ApplicationRecord
  mount_uploaders :images, EventImageUploader
  serialize :images, JSON
  # 排序
  include RankedModel
  ranks :row_order

  has_many :registrations, dependent: :destroy
  has_many :tickets, dependent: :destroy, inverse_of: :event
  belongs_to :category, optional: true
  # 某些版本的Rails 有个accepts_nested_attributes_for 的bug 让has_many 故障了，需要额外补上inverse_of 参数，不然存储时会找不到tickets
  accepts_nested_attributes_for :tickets, reject_if: :all_blank, allow_destroy: true

  validates_presence_of :name, :random_id
  validates_uniqueness_of :random_id, message: '必须不相同'
  validates_format_of :random_id, with: /\A[a-z0-9\-]+\z/, message: '无效的格式'

  before_validation :generate_random_id, on: :create

  # 加上状态字段的验证
  STATUS = %W[\u8349\u7A3F \u516C\u5F00 \u79C1\u4EBA].freeze
  validates_inclusion_of :status, in: STATUS

  # 在调用路由方法时，Rails 默认都会用 to_param 方法来转换 ID,
  #  def to_param
  #    self.id
  #  end

  def to_param
    # "#{self.id}-#{self.name}"
    random_id
  end

  protected

  def generate_random_id
    self.random_id ||= SecureRandom.uuid
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminController
  before_action :require_editor!
  def index
    @events = Event.rank(:row_order).all
  end

  def show
    @event = Event.find_by_random_id!(params[:id])
    colors = ['rgba(255, 99, 132, 0.2)',
              'rgba(54, 162, 235, 0.2)',
              'rgba(255, 206, 86, 0.2)',
              'rgba(75, 192, 192, 0.2)',
              'rgba(153, 102, 255, 0.2)',
              'rgba(255, 159, 64, 0.2)']

    ticket_names = @event.tickets.map(&:name)

    status_colors = { 'confirmed' => '#FF6384',
                      'pending' => '#36A2EB' }

    @data1 = {
      labels: ticket_names,
      datasets: Registration::STATUS.map do |s|
                  {
                    label: I18n.t(s, scope: 'registration.status'),
                    data: @event.tickets.map { |t| t.registrations.by_status(s).count },
                    backgroundColor: status_colors[s],
                    borderWidth: 1
                  }
                end
    }

    if @event.registrations.any?
      dates = (@event.registrations.order('id ASC').first.created_at.to_date..Date.today).to_a
      @data3 = {
        labels: dates,
        datasets: Registration::STATUS.map do |s|
          {
            label: I18n.t(s, scope: 'registration.status'),
            data: dates.map  do |d|
              @event.registrations.by_status(s).where('created_at >= ? AND created_at <= ?', d.beginning_of_day, d.end_of_day).count
            end,
            borderColor: status_colors[s]
          }
        end
      }
     end
  end

  def new
    @event = Event.new
    @event.tickets.build
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to admin_events_path
    else
      render 'new'
    end
  end

  def edit
    @event = Event.find_by_random_id!(params[:id])
    @event.tickets.build if @event.tickets.empty?
  end

  def update
    @event = Event.find_by_random_id!(params[:id])

    if @event.update(event_params)
      redirect_to admin_events_path
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find_by_random_id!(params[:id])
    @event.destroy

    redirect_to admin_events_path
  end

  def bulk_update
    # 关于 Array(params[:ids] 这个用法，如果是 Array([1,2,3]) 会等同于 [1,2,3] 没变，但是 Array[nil] 会变成 [] 空数组，这可以让 .each 方法不会因为 nil.each 而爆错。
    # 如果不这样处理，在没有勾选任何活动就送出的情况，就会爆出 NoMethodError 错误。除非你额外检查 params[:id] 如果是 nil 就返回，但不如用 Array 来的精巧
    total = 0
    Array(params[:ids]).each do |event_id|
      event = Event.find(event_id)
      if params[:commit] == I18n.t(:bulk_update)
        event.status = params[:event_status]
        total += 1 if event.save
      elsif params[:commit] == I18n.t(:bulk_delete)
        event.destroy
        total += 1
      end
    end

    flash[:alert] = "成功完成 #{total} 项"
    redirect_to admin_events_path
  end

  def reorder
    @event = Event.find_by_random_id!(params[:id])
    @event.row_order_position = params[:position]
    @event.save!

    respond_to do |format|
      format.html { redirect_to admin_events_path }
      format.json { render json: { message: 'ok' } }
    end
  end

  protected

  def event_params
    params.require(:event).permit(:name, :description, :random_id, :status, :remove_images, :category_id, tickets_attributes: %i[id name description price _destroy], images: [])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.rank(:row_order).all
  end

  def show
    @event = Event.find_by_random_id!(params[:id])
  end

end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_form.html.erb
<% if @event.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@event.errors.count, "error") %> prohibited this person from being saved:</h2>

  <ul>
    <% @event.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <%= f.label :名称 %>
  <%= f.text_field :name, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :描述 %>
  <%= f.cktext_area :description, ckeditor: { language: 'zh-CN'} %>
</div>

<div class="form-group">
  <%= f.label :category_id %>
  <%= f.select :category_id, Category.all.map{ |s| [s.name, s.id] }, {}, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :status %>
  <% Event::STATUS.each do |status| %>
  <label>
    <%= f.radio_button :status, status %>
    <%= t(status, scope: "event.status") %>
  </label>
  <% end %>
</div>

<div class="form-group">
  <%= f.label :random_id %>
  <%= f.text_field :random_id, :required => true, :class => "form-control" %>
  <p class="help-block">限小写英数字及横线，将作为网址的一部分</p>
</div>

<div class="form-group">
  <%= f.label :images %>
  <%= f.file_field :images, :multiple => true, :class => "form-control" %>
  <% if f.object.images.present? %>
  <label>
    <%= f.check_box :remove_images %> 删除图档
  </label>
  <% f.object.images.each do |i| %>
  <%= link_to i.filename, i.url, :target => "_blank" %>
  <% end %>
  <% end %>
</div>

<%= f.nested_fields_for :tickets do |ff| %>
<fieldset style="border-left: 5px solid #bbb; margin-bottom: 10px; padding: 10px;">
  <legend>票种</legend>
  <div class="form-group">
    <%= ff.label :名称 %>
    <%= ff.text_field :name, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= ff.label :价格 %>
    <%= ff.number_field :price, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= ff.label :描述 %>
    <%= ff.text_area :description, :class => "form-control" %>
  </div>
</fieldset>
<%= ff.remove_nested_fields_link "移除这个票种", :class => "btn btn-danger" %>

<% end %>

<p class="text-right">
  <%= f.add_nested_fields_link :tickets, "新增票种", :class => "btn btn-default" %>
</p>

<script>
  $("#event_category_id").select2({ theme: "bootstrap" });
</script>

<%# 其中 event_category_id 是这个 select 下拉选单的 HTML ID %>

app/views/admin/events/edit.html.erb
<h1>Edit Event</h1>

<%= form_for [:admin, @event] do |f| %>

<%= render :partial => "form", :locals => { :f => f } %>

<div class="form-group">
  <%= f.submit "Update", :class => "btn btn-primary" %>
  <%= link_to "Cancel", admin_events_path %>
</div>
<% end %>

app/views/admin/events/index.html.erb
<h1><%= t("admin.event_list") %></h1>

<p class="text-right">
<%= link_to "新建活动", new_admin_event_path, :class => "btn btn-primary" %>
</p>

<%= form_tag bulk_update_admin_events_path, :class => "form-inline" do %>
<%# <p><%= submit_tag "批次删除", :class => "btn btn-danger", :data => { :confirm => "确定要删除吗?" } %>
  <p>
  <%= select_tag :event_status, options_for_select( Event::STATUS.map{ |s| [t(s, :scope => "event.status"), s] }), :class => "form-control" %>
  <%# <%= submit_tag t(:bulk_update), :class => "btn btn-primary" %> 
  <%= submit_tag t(:bulk_delete), :class => "btn btn-danger", :data => { :confirm => "Are you sure?" } %>
  </p>
<table class="table">
  <thead>
    <tr>
      <th><%= check_box_tag "全选", "1", false, :id => "toggle_all" %></th>
      <th>活动名称</th>
      <th>操作</th>
    </tr>
  </thead>
    <tbody class="sortable">
      <% @events.each do |event| %>
        <tr data-reorder-url="<%= reorder_admin_event_path(event) %>">
          <td>
            <%= check_box_tag "ids[]", event.id %>
          </td>
          <td>
            <span class="sortable_icon">☰</span>
            <%= link_to event.name, admin_event_path(event) %>
          </td>

          <td>
            <%# 在路由方法 reorder_admin_event_path 中，我们额外传了 :position 参数，等会在 controller 中就可以接收到 params[:position] 代表移动的方式 %>
            <%= link_to "置顶", reorder_admin_event_path(event, :position => :first), :method => :post, :class => "btn btn-default" %>
            <%= link_to "置底", reorder_admin_event_path(event, :position => :last), :method => :post, :class => "btn btn-default" %>
            <%= link_to "Registrations", admin_event_registrations_path(event), :class => "btn btn-default" %>
            <%= link_to "票种", admin_event_tickets_path(event), :class => "btn btn-default" %>
            <%= link_to "编辑", edit_admin_event_path(event), :class => "btn btn-default" %>
            <%= link_to "删除", admin_event_path(event), :method => "delete", :data => { :confirm => "确定要删除吗?" }, :class => "btn btn-danger" %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

  <script>
   // 这个 javascript 会绑事件在 #toggle_all 核选方块上，来做全选效果
   $("#toggle_all").click(function(){
     if ( $(this).prop("checked") ) {
       $("input[name='ids[]']").prop("checked", true);
     } else {
       $("input[name='ids[]']").prop("checked", false);
     }
   })
     $( ".sortable" ).sortable({
    axis: 'y',       // 限制只能上下拖拉
    items: 'tr',     // 拖拉整个 tr
    cursor: 'move',  // 变更拖拉时的 icon
    handle: ".sortable_icon",  // 限制只有点 ☰ 才能开始拖拉，砍掉这行的话，会是整个 tr 都可以进行拖拉，你可以试试看
    stop: function(e, ui){     // 当拖拉结束时，会调用这个方法
      ui.item.children('td').effect('highlight', {}, 1000)
    },
    update: function(e, ui) {   // 当拖拉结束并且 DOM 上的位置变更时，会调用这个方法
      reorder_url = ui.item.data('reorder-url')
      position = ui.item.index()  // 取得顺序
      $.ajax({
       type: 'POST',
       url: reorder_url,
       dataType: 'json',
       data: { position: position }
      })
    }
  });
 </script>

app/views/admin/events/new.html.erb
<h1>New Event</h1>

<%= form_for [:admin, @event] do |f| %>

  <%= render :partial => "form", :locals => { :f => f } %>

  <div class="form-group">
    <%= f.submit "Create", :class => "btn btn-primary" %>
    <%= link_to "Cancel", admin_events_path %>
  </div>
<% end %>

app/views/admin/events/show.html.erb
<h1><%= @event.name %></h1>

<p>
    <%= link_to "打開前台", event_path(@event), :target => "_blank", :class => "btn btn-primary" %>
</p>

<%= simple_format @event.description %>

<script src="//cdn.bootcss.com/Chart.js/2.5.0/Chart.bundle.min.js"></script>

<canvas id="myChart1" width="400" height="200"></canvas>
<script>
    const ctx1 = document.getElementById("myChart1");
    const myChart1 = new Chart(ctx1, {
        type: 'bar',
        data: <%= raw @data1.to_json %>,
            options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
 });
</script>
<hr>

<canvas id="myChart3" width="400" height="200"></canvas>
<script>
    const ctx3 = document.getElementById("myChart3");
    const myChart3 = new Chart(ctx3, {
        type: 'line',
        data: <%= raw @data3.to_json %>,
            options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
  });
</script>

<hr>

<canvas id="myChart" width="400" height="200"></canvas>
<script>
    var ctx = document.getElementById("myChart");
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: ["Red", "Blue", "Yellow", "Green", "Purple", "Orange"],
            datasets: [{
                label: '# of Votes',
                data: [12, 19, 3, 5, 2, 3],
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(255,99,132,1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });
</script>