config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # :user，跟 resources :users 相比，单数的路由少了 index action，并且网址上不会有 ID，路由方法也皆为单数不需要参数，例如 user_path、edit_user_path。
  # 会这样设计的原因是对前台用户而言，
  # 编辑用户资料就是编辑自己的资料，所以这个单数的用意是指唯一自己，用户也不能修改其他人的资料，因此在controller 里面是写@user = current_user，而不是根据params[:id] 去捞不同用户。
  resource :user

  resources :events do
    resources :registrations do
      member do
        get 'steps/1' => 'registrations#step1', :as => :step1
        patch 'steps/1/update' => 'registrations#step1_update', :as => :update_step1
        get 'steps/2' => 'registrations#step2', :as => :step2
        patch 'steps/2/update' => 'registrations#step2_update', :as => :update_step2
        get 'steps/3' => 'registrations#step3', :as => :step3
        patch 'steps/3/update' => 'registrations#step3_update', :as => :update_step3
      end
    end
  end

  namespace :admin do
    root 'events#index'

    resources :versions do
      post :undo
    end

    resources :events do
      resources :registrations, controller: 'event_registrations'
      resources :tickets, controller: 'event_tickets'
      member do
        post :reorder
      end
      collection do
        post :bulk_update
      end
    end
    resources :users do
      # 因为默认的 controller 的命名是 profiles，这里我们偏好自定义命名改为user_profiles
      resource :profile, controller: 'user_profiles'
    end
  end

  root 'events#index'
  get '/faq', to: 'pages#faq'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :memberships
  has_many :groups, through: :memberships
  has_one :profile
  has_many :registrations
  # 可以在更新 User 时，也顺便可以更新 Profile 资料
  accepts_nested_attributes_for :profile
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ROLES = ["admin", "editor"]

  def display_name
    email.split('@').first
  end

  def is_admin?
    self.role == "admin"
  end

  def is_editor?
    ["admin", "editor"].include?(self.role)
  end
end

app/controllers/admin/users_controller.rb
# class Admin::UsersController < ApplicationController
# Rails 的 controller 默认会继承自 ApplicationController，这里改成继承自 AdminController，这样定义在 app/controllers/admin_controller.rb 的所有方法都会被继承下来，包括 layout "admin"
class Admin::UsersController < AdminController
  before_action :require_admin!
  def index
    # @users = User.all
    # 为了避免 N+1 Query 效能问题, 改成下面的
    @users = User.includes(:groups).all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path
    else
      render "edit"
    end
  end

  protected

  def user_params
    params.require(:user).permit(:email, :role, :group_ids => [])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "修改成功"
      redirect_to user_path
    else
      flash[:error] = "出错了"
      render 'edit'
    end
  end
  
  protected

  def find_user
    @user = current_user
    # 如果没有 @user.profile，要先新建一个
    @user.create_profile unless @user.profile
  end

  def user_params
    params.require(:user).permit(:time_zone,  :profile_attributes => [:id, :legal_name, :birthday, :location, :education, :occupation, :bio, :specialty] )
  end
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>编辑用户</h1>

<% if @user.errors.any? %>
<div id="error_explanation">
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= form_for [:admin, @user] do |f| %>

<div class="form-group">
  <%= f.label :email %>
  <%= f.text_field :email, class: "form-control" %>
</div>

<!-- :include_blank => true 参数，这会让下拉选单多一个空的 nil 空选项 -->
<div class="form-group">
  <%= f.label :role %>
  <%= f.select :role, User::ROLES.map{ |x| [t(x, :scope => "user.role"), x] }, { :include_blank => true }, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :group_ids %>
  <%# <%= f.collection_check_boxes(:group_ids, Group.all, :id, :name)  %>
  <%# 也可以用 Select2 来改进 UI %>
  <%= f.select :group_ids, Group.all.map{ |g| [g.name, g.id] }, {}, :multiple => true, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.submit "确定", class: "btn btn-primary" %>
  <%= link_to "取消", admin_users_path %>
</div>

<% end %>

<script>
  $("#user_group_ids").select2()
</script>

app/views/admin/users/index.html.erb
<h1>后台用户</h1>

<table>
  <tr>
  <th>ID</th>
  <th>邮箱</th>
  <th>操作</th>
</tr>
<% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.email %></td>
     <td>
      <% user.groups.each do |g| %>
        <%= g.name %>
      <% end %>
     </td>
    <td><%= link_to "编辑", edit_admin_user_path(user), :class => "btn btn-default" %></td>
    <td><%= link_to "编辑个人信息", edit_admin_user_profile_path(user), :class => "btn btn-default" %></td>
  </tr>
<% end %>
</table>