config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # :user，跟 resources :users 相比，单数的路由少了 index action，并且网址上不会有 ID，路由方法也皆为单数不需要参数，例如 user_path、edit_user_path。
  # 会这样设计的原因是对前台用户而言，
  # 编辑用户资料就是编辑自己的资料，所以这个单数的用意是指唯一自己，用户也不能修改其他人的资料，因此在controller 里面是写@user = current_user，而不是根据params[:id] 去捞不同用户。
  resource :user

  resources :events do
    resources :registrations do
      member do
        get 'steps/1' => 'registrations#step1', :as => :step1
        patch 'steps/1/update' => 'registrations#step1_update', :as => :update_step1
        get 'steps/2' => 'registrations#step2', :as => :step2
        patch 'steps/2/update' => 'registrations#step2_update', :as => :update_step2
        get 'steps/3' => 'registrations#step3', :as => :step3
        patch 'steps/3/update' => 'registrations#step3_update', :as => :update_step3
      end
    end
  end

  namespace :admin do
    root 'events#index'

    resources :versions do
      post :undo
    end

    resources :events do
      resources :registrations, controller: 'event_registrations'
      resources :tickets, controller: 'event_tickets'
      member do
        post :reorder
      end
      collection do
        post :bulk_update
      end
    end
    resources :users do
      # 因为默认的 controller 的命名是 profiles，这里我们偏好自定义命名改为user_profiles
      resource :profile, controller: 'user_profiles'
    end
  end

  root 'events#index'
  get '/faq', to: 'pages#faq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  mount_uploaders :images, EventImageUploader
  serialize :images, JSON
  # 排序
  include RankedModel
  ranks :row_order

  has_many :registrations, dependent: :destroy
  has_many :tickets, dependent: :destroy, inverse_of: :event
  belongs_to :category, optional: true
  # 某些版本的Rails 有个accepts_nested_attributes_for 的bug 让has_many 故障了，需要额外补上inverse_of 参数，不然存储时会找不到tickets
  accepts_nested_attributes_for :tickets, reject_if: :all_blank, allow_destroy: true

  validates_presence_of :name, :random_id
  validates_uniqueness_of :random_id, message: '必须不相同'
  validates_format_of :random_id, with: /\A[a-z0-9\-]+\z/, message: '无效的格式'

  before_validation :generate_random_id, on: :create

  # 加上状态字段的验证
  STATUS = %W[\u8349\u7A3F \u516C\u5F00 \u79C1\u4EBA].freeze
  validates_inclusion_of :status, in: STATUS

  # 在调用路由方法时，Rails 默认都会用 to_param 方法来转换 ID,
  #  def to_param
  #    self.id
  #  end

  def to_param
    # "#{self.id}-#{self.name}"
    random_id
  end

  protected

  def generate_random_id
    self.random_id ||= SecureRandom.uuid
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :memberships
  has_many :users, through: :memberships
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/registration.rb
class Registration < ApplicationRecord
  # 透过 attr_accessor :current_step 我们增加一个虚拟属性(也就是数据库中并没有这个字段)来代表目前做到哪一步
  attr_accessor :current_step
  STATUS = ["pending", "confirmed"]
  # 软删除和版本控制
  has_paper_trail
  # 设定状态是其中的一种
  validates_inclusion_of :status, in: STATUS
  validates_presence_of :status, :ticket_id
  # :if 这个参数可以设定调用那一个方法来决定要不要启用这个验证，回传 true 就是要，回传 false 就是不要
  validates_presence_of :name, :email, :cellphone, :if => :should_validate_basic_data?
  validates_presence_of :name, :email, :cellphone, :bio, :if => :should_validate_all_data?
  # 自定义一个资料验证, validate 可以增加自定义的资料验证，后面的 :on => :create 参数可以指定只有新建才会验证(默认是新建跟修改都会验证)
  validate :check_event_status, :on => :create

  # scope 的作用是将常用的查询条件宣告起来，方便重复使用
  scope :by_status, ->(s){ where( :status => s ) }
  scope :by_ticket, ->(t){ where( :ticket_id => t ) }

  belongs_to :event
  belongs_to :ticket
  belongs_to :user, :optional => true

  before_validation :generate_uuid, :on => :create

  def to_param
    self.uuid
  end

  def should_validate_basic_data?
    current_step == 2  # 只有做到第二步需要验证
  end

  def should_validate_all_data?
    current_step == 3 || status == "confirmed"  # 做到第三步，或最后状态是 confirmed 时需要验证
  end

  protected

  # 新建的时候乱数产生一个 UUID 来当作网址 ID。
  def generate_uuid
    self.uuid = SecureRandom.uuid
  end

  # 如果活动的状态是 draft 草稿，则不允许新增报名,* 验证不通过时，会用errors.add 增加错误讯息，第一个参数是字段名称，第二个参数是错误讯息
  # 因为表单上并没有 event_id 这个输入框，所以就算写成 errors.add(:event_id, "活动尚未开放报名") 
  # 也没有地方显示出来。依照惯例，任何不属于某个字段的错误，我们会放在 :base 上。
  def check_event_status
    if self.event.status == "draft"
      errors.add(:base, "活动尚未开放报名")
    end
  end


end

app/models/ticket.rb
class Ticket < ApplicationRecord
  validates_presence_of :name, :price
  belongs_to :event
  has_many :registrations
end

app/models/user.rb
class User < ApplicationRecord
  has_many :memberships
  has_many :groups, through: :memberships
  has_one :profile
  has_many :registrations
  # 可以在更新 User 时，也顺便可以更新 Profile 资料
  accepts_nested_attributes_for :profile
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ROLES = ["admin", "editor"]

  def display_name
    email.split('@').first
  end

  def is_admin?
    self.role == "admin"
  end

  def is_editor?
    ["admin", "editor"].include?(self.role)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  layout 'admin'

  protected

  def require_editor!
    unless current_user.is_editor?
      flash[:alert] = '您的权限不足'
      redirect_to root_path
     end
  end

  def require_admin!
    unless current_user.is_admin?
      flash[:alert] = '您的权限不足'
      redirect_to root_path
     end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.rank(:row_order).all
  end

  def show
    @event = Event.find_by_random_id!(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "修改成功"
      redirect_to user_path
    else
      flash[:error] = "出错了"
      render 'edit'
    end
  end
  
  protected

  def find_user
    @user = current_user
    # 如果没有 @user.profile，要先新建一个
    @user.create_profile unless @user.profile
  end

  def user_params
    params.require(:user).permit(:time_zone,  :profile_attributes => [:id, :legal_name, :birthday, :location, :education, :occupation, :bio, :specialty] )
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>RailsRecipes</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
          aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/admin/">Rails Recipes</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <% if current_user %>
          <% if current_user.is_editor? %>
          <li class="active"><%= link_to('活动管理', admin_events_path) %></li>
          <% end %>
          <% if current_user.is_admin? %>
          <li class="active"><%= link_to('用户管理', admin_users_path) %></li>
          <% end %>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
              aria-expanded="false"><span class="glyphicon glyphicon-user"></span> <%= current_user.display_name %>
              <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "回到前台", root_path %></li>
              <li><%= link_to('修改密码', edit_registration_path(:user)) %></li>
              <li><%= link_to('登出', destroy_user_session_path, :method => :delete) %></li>
            </ul>
          </li>
          <% else %>
          <li><%= link_to('注册', new_registration_path(:user)) %></li>
          <li><%= link_to('登入', new_session_path(:user)) %></li>
          <% end %>
        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
  </nav>

  <div class="container" style="padding-top: 60px">

    <% if notice %>
    <p class="notice alert-success"><%= notice %></p>
    <% end %>

    <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </div>
</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRecipes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">


      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Rails Recipes 前台</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><%= link_to "活动一览", events_path %></li>
            </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user"></span> <%= current_user.display_name %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to('管理员', admin_events_path) %></li>
                  <li><%= link_to('我的个人资料', user_path) %></li>
                  <li><%= link_to('修改个人资料', edit_user_path) %></li>
                  <li><%= link_to('修改密码', edit_registration_path(:user)) %></li>
                  <li><%= link_to('登出', destroy_user_session_path, :method => :delete) %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to('注册', new_registration_path(:user)) %></li>
              <li><%= link_to('登入', new_session_path(:user)) %></li>
            <% end %>
          </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

  <% if notice %>
   <p class="notice alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>


      <%= yield %>
      <%= link_to "FAQ", faq_path %>
      <%= link_to "中文版", controller: controller_name, action: action_name, locale: "zh-CN" %>
      <%= link_to "English", controller: controller_name, action: action_name, locale: "en" %>
    </div>
  </body>
</html>